# Generated by Django 4.2.4 on 2023-09-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffeeName', models.TextField(default='', max_length=50)),
                ('coffeeImage', models.ImageField(default='', upload_to='')),
                ('coffeeSmall', models.IntegerField(default=20)),
                ('coffeeBig', models.IntegerField(default=20)),
            ],
        ),
    ]
