# Generated by Django 4.2.4 on 2023-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0002_alter_coffee_coffeename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=60)),
                ('text', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='coffee',
            name='coffeeImage',
            field=models.ImageField(upload_to='images'),
        ),
    ]
